// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCatalog.Infrastructure.Migrations.Factory;

#nullable disable

namespace MovieCatalog.Infrastructure.Migrations.Migrations
{
    [DbContext(typeof(MovieCatalogMigrationsDbContext))]
    [Migration("20250816152720_Update_QueryHistoryEntity_TableRename")]
    partial class Update_QueryHistoryEntity_TableRename
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("MovieCatalog.Domain.Entities.QueryHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryTitle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTimestamp")
                        .IsDescending();

                    b.ToTable("QueryHistory", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
